---

name: CI

on:
  pull_request:
    branches: [devel]

  push:
    branches: [devel]

jobs:
  podman:
    runs-on: ubuntu-24.04
    name: Podman
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install tox

      - name: Build EE with Podman
        run: |
          tox -e podman

  docker:
    runs-on: ubuntu-24.04
    name: Docker
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: 'pip'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install dependencies
        run: |
          pip install tox

      - name: Build EE with Docker
        env:
          DOCKER_BUILDKIT: 1
        run: |
          tox -e docker
